export const dataShow = [
  {
    id: "XnqM9Zrpg5raQoJvivl8",
    categoryId: "X63OeZXLKAqyVcAm38aT",
    unit: "g",
    createdDate: {
      seconds: 1627293128,
      nanoseconds: 29000000,
    },
    keywords: [
      "c",
      "ca",
      "ca ",
      "ca r",
      "ca ro",
      "ca rot",
      "r",
      "ro",
      "rot",
      "rot ",
      "rot c",
      "rot ca",
    ],
    description: "Nhiều vitamin A",
    discount: 10,
    productImage:
      "https://cdn.tgdd.vn/Files/2019/09/18/1199521/thit-trau-gac-bep-la-gi-an-co-tot-khong--11.jpg",
    productName: "Thịt Bò Gác Bếp",
    price: 29000,
    quantity: 4324,
    updatedDate: {
      seconds: 1628330357,
      nanoseconds: 697000000,
    },
    rating: 5,
  },
  {
    id: "j8bu2hpYygc572Zwe3c5",
    productImage:
      "http://media.dulich24.com.vn/bai-viet/nhung-mon-dac-san-noi-tieng-vung-tay-bac-40090222/233e059d-c30e-4325-aa81-583e059088e4.jpg",
    price: 123000,
    keywords: [
      "n",
      "ng",
      "ngo",
      "ngo ",
      "ngo n",
      "ngo ne",
      "ngo nep",
      "n",
      "ne",
      "nep",
      "nep ",
      "nep n",
      "nep ng",
      "nep ngo",
    ],
    createdDate: {
      seconds: 1627276925,
      nanoseconds: 246000000,
    },
    unit: "kg",
    quantity: 21,
    discount: 71,
    rating: 3,
    description:
      "Xôi ngũ sắc là món ăn phổ biến trong các dịp lễ tết của đồng bào Tây Bắc, đặc biệt với người Thái tại Yên Bái. Tùy theo nhu cầu mà người chế biến có thể sử dụng nhiều hoặc ít màu đi.",
    categoryId: "wVaMcDH4yni65ls9aY3C",
    productName: "Xôi ngũ sắc",
  },

  {
    id: "j8bu2hpYygc572Zwe3c5",
    productImage:
      "http://media.dulich24.com.vn/bai-viet/nhung-mon-dac-san-noi-tieng-vung-tay-bac-40090222/fbf447cb-db44-4f00-9ae9-8dc9c3058baa.jpg",
    price: 123000,
    keywords: [
      "n",
      "ng",
      "ngo",
      "ngo ",
      "ngo n",
      "ngo ne",
      "ngo nep",
      "n",
      "ne",
      "nep",
      "nep ",
      "nep n",
      "nep ng",
      "nep ngo",
    ],
    createdDate: {
      seconds: 1627276925,
      nanoseconds: 246000000,
    },
    unit: "kg",
    quantity: 21,
    discount: 71,
    rating: 3,
    description:
      "Bánh chưng đen là món ăn độc đáo của người Thái Mường Lò tại tỉnh Yên Bái. ",
    categoryId: "wVaMcDH4yni65ls9aY3C",
    productName: "Bánh Chưng Đen",
  },

  {
    id: "j8bu2hpYygc572Zwe3c5",
    productImage:
      "http://media.dulich24.com.vn/diemden/thai-nguyen-7514/16b5c638-a1ce-4f0c-ba6f-2483cc8c5140-14.jpg",
    price: 123000,
    keywords: [
      "n",
      "ng",
      "ngo",
      "ngo ",
      "ngo n",
      "ngo ne",
      "ngo nep",
      "n",
      "ne",
      "nep",
      "nep ",
      "nep n",
      "nep ng",
      "nep ngo",
    ],
    createdDate: {
      seconds: 1627276925,
      nanoseconds: 246000000,
    },
    unit: "kg",
    quantity: 21,
    discount: 71,
    rating: 3,
    description:
      "Giống như các dân tộc thiểu số khác ở Thái Nguyên, dân tộc Tày có một loại đặc sản riêng thường làm vào Tết Thanh minh, đó là bánh ngải ",
    categoryId: "wVaMcDH4yni65ls9aY3C",
    productName: "Bánh ngải",
  },

  {
    id: "j8bu2hpYygc572Zwe3c5",
    productImage:
      "http://media.dulich24.com.vn/bai-viet/nhung-mon-dac-san-noi-tieng-vung-tay-bac-40090222/8b3bfda4-f275-4540-b502-ea0be9560fb7.jpg",
    price: 123000,
    keywords: [
      "n",
      "ng",
      "ngo",
      "ngo ",
      "ngo n",
      "ngo ne",
      "ngo nep",
      "n",
      "ne",
      "nep",
      "nep ",
      "nep n",
      "nep ng",
      "nep ngo",
    ],
    createdDate: {
      seconds: 1627276925,
      nanoseconds: 246000000,
    },
    unit: "kg",
    quantity: 21,

    discount: 71,
    rating: 3,
    description:
      "Măng đắng là sản vật và là món ăn rất phổ biến của người Điện Biên. Với măng đắng, người ta có thể chế biến thành nhiều món ăn hấp dẫn như xào, luộc, nướng, hầm xương.",
    categoryId: "Y4wlWVRg8AUjnGt8zjJC",
    productName: "MĂNG RỪNG",
  },

  {
    id: "j8bu2hpYygc572Zwe3c5",
    productImage:
      "http://media.dulich24.com.vn/bai-viet/nhung-mon-dac-san-noi-tieng-vung-tay-bac-40090222/bf3dd980-8bc3-499e-a511-acf30841f510.jpg",
    price: 123000,
    keywords: [
      "n",
      "ng",
      "ngo",
      "ngo ",
      "ngo n",
      "ngo ne",
      "ngo nep",
      "n",
      "ne",
      "nep",
      "nep ",
      "nep n",
      "nep ng",
      "nep ngo",
    ],
    createdDate: {
      seconds: 1627276925,
      nanoseconds: 246000000,
    },
    unit: "kg",
    quantity: 21,
    discount: 71,
    rating: 5,
    description:
      "Mật ong Mù Cang Chải là một trong những đặc sản của Yên Bái. Từ lâu nó đã được người tiêu dùng gần xa ưa chuộng vì chất lượng mật tốt, màu vàng óng, ",
    categoryId: "wVaMcDH4yni65ls9aY3C",
    productName: "Mật Ong Mù Căng Chải ",
  },

  {
    id: "j8bu2hpYygc572Zwe3c5",
    productImage:
      "http://media.dulich24.com.vn/bai-viet%5Can-gi-o-ha-giang-dac-san-ha-giang-quan-an-ngon-o-ha-giang-61112851%5Cmon-ngon-o-ha-giang-7.jpg",
    price: 123000,
    keywords: [
      "n",
      "ng",
      "ngo",
      "ngo ",
      "ngo n",
      "ngo ne",
      "ngo nep",
      "n",
      "ne",
      "nep",
      "nep ",
      "nep n",
      "nep ng",
      "nep ngo",
    ],
    createdDate: {
      seconds: 1627276925,
      nanoseconds: 246000000,
    },
    unit: "kg",
    quantity: 21,
    discount: 71,
    rating: 3,
    description:
      "Hà Giang là một vùng phì nhiêu với những loại gạo nếp thơm ngon nổi tiếng thì cơm lam Bắc Mê đang dần trở thành một đặc sản đặc trưng của đồng bào dân tộc Tày nơi đây.    ",
    categoryId: "wVaMcDH4yni65ls9aY3C",
    productName: "Cơm Lam Bắc Mê",
  },

  {
    id: "j8bu2hpYygc572Zwe3c5",
    productImage:
      "http://media.dulich24.com.vn/bai-viet%5Can-gi-o-ha-giang-dac-san-ha-giang-quan-an-ngon-o-ha-giang-61112851%5Cmon-ngon-o-ha-giang-16.jpg",
    price: 123000,
    keywords: [
      "n",
      "ng",
      "ngo",
      "ngo ",
      "ngo n",
      "ngo ne",
      "ngo nep",
      "n",
      "ne",
      "nep",
      "nep ",
      "nep n",
      "nep ng",
      "nep ngo",
    ],
    createdDate: {
      seconds: 1627276925,
      nanoseconds: 246000000,
    },
    unit: "kg",
    quantity: 21,
    discount: 71,
    rating: 3,
    description:
      "Để làm nhân lạp xưởng người ta chọn loại thịt nửa nạc nửa mỡ. Bởi nạc nhiều, lạp xưởng sẽ khô, sác; mỡ nhiều, lạp xưởng sẽ nhão, ăn mau ngấy nên loại thịt thích hợp nhất để làm lạp xưởng là thịt vai.",
    categoryId: "X63OeZXLKAqyVcAm38aT",
    productName: "Lạp xưởng gac bếp",
  },

  {
    id: "j8bu2hpYygc572Zwe3c5",
    productImage:
      "http://media.dulich24.com.vn/bai-viet/nhung-mon-dac-san-noi-tieng-vung-tay-bac-40090222/c8c55c5e-facc-4ff4-aba4-e73675814c02.JPG",
    price: 123000,
    keywords: [
      "n",
      "ng",
      "ngo",
      "ngo ",
      "ngo n",
      "ngo ne",
      "ngo nep",
      "n",
      "ne",
      "nep",
      "nep ",
      "nep n",
      "nep ng",
      "nep ngo",
    ],
    createdDate: {
      seconds: 1627276925,
      nanoseconds: 246000000,
    },
    unit: "kg",
    quantity: 21,
    discount: 71,
    rating: 3,
    description:
      "Thứ nếp này khi được đồ thành xôi thì có vị dẻo thơm đặc biệt, còn khi chế biến thành cốm thì lại có thêm hương vị thật ngọt ngào, thanh mát",
    categoryId: "wVaMcDH4yni65ls9aY3C",
    productName: "Cốm Tú Lệ",
  },
  {
    id: "P09oVvIY7kV9wkwvuNzB",
    productName: "Thịt trâu gác bếp",
    rating: 4,
    quantity: 31,
    createdDate: {
      seconds: 1627278142,
      nanoseconds: 452000000,
    },
    description: "Thịt trâu gác bếp Tây Bắc",
    productImage:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQE9FiegypziYE6caFxdQCVFFdmcfw8-6vVfA&usqp=CAU",
    unit: "kg",
    categoryId: "X63OeZXLKAqyVcAm38aT",
    price: 169000,
    discount: 20,
    keywords: [
      "c",
      "ca",
      "cam",
      "cam ",
      "cam c",
      "cam ca",
      "cam can",
      "cam canh",
      "c",
      "ca",
      "can",
      "canh",
      "canh ",
      "canh c",
      "canh ca",
      "canh cam",
    ],
  },
  {
    id: "HHuv99GRSCslKbYXTeuA",
    createdDate: {
      seconds: 1627278094,
      nanoseconds: 965000000,
    },
    rating: 2,
    productImage:
      "http://amthuctaybac.vn/images/stories/virtuemart/product/resized/18079967058_0567dcf308_o_0x250.png",
    categoryId: "jqaq8roGL4QRZKn9Hpc7",
    discount: 32,
    unit: "Sản phẩm",
    keywords: [
      "d",
      "du",
      "dui",
      "dui ",
      "dui g",
      "dui ga",
      "dui ga ",
      "dui ga t",
      "dui ga ta",
      "d",
      "du",
      "dui",
      "dui ",
      "dui t",
      "dui ta",
      "dui ta ",
      "dui ta g",
      "dui ta ga",
      "g",
      "ga",
      "ga ",
      "ga d",
      "ga du",
      "ga dui",
      "ga dui ",
      "ga dui t",
      "ga dui ta",
      "g",
      "ga",
      "ga ",
      "ga t",
      "ga ta",
      "ga ta ",
      "ga ta d",
      "ga ta du",
      "ga ta dui",
      "t",
      "ta",
      "ta ",
      "ta d",
      "ta du",
      "ta dui",
      "ta dui ",
      "ta dui g",
      "ta dui ga",
      "t",
      "ta",
      "ta ",
      "ta g",
      "ta ga",
      "ta ga ",
      "ta ga d",
      "ta ga du",
      "ta ga dui",
    ],
    productName: "Mật Ong Nuôi",
    quantity: 41,
    description: "Mật Ong Nuôi, nhiều mật",
    price: 62000,
    updatedDate: {
      seconds: 1629015186,
      nanoseconds: 115000000,
    },
  },
  {
    id: "GuefZDJNIE5mntFypO3E",
    productName: "Thịt lợn gác bếp",
    quantity: 100,
    unit: "Sản phẩm",
    rating: 4,
    categoryId: "X63OeZXLKAqyVcAm38aT",
    description: "Xẻ thịt trong ngày",
    createdDate: {
      seconds: 1627278046,
      nanoseconds: 435000000,
    },
    keywords: [
      "b",
      "ba",
      "ban",
      "banh",
      "banh ",
      "banh m",
      "banh mi",
      "banh mi ",
      "banh mi v",
      "banh mi vu",
      "banh mi vun",
      "banh mi vung",
      "b",
      "ba",
      "ban",
      "banh",
      "banh ",
      "banh v",
      "banh vu",
      "banh vun",
      "banh vung",
      "banh vung ",
      "banh vung m",
      "banh vung mi",
      "m",
      "mi",
      "mi ",
      "mi b",
      "mi ba",
      "mi ban",
      "mi banh",
      "mi banh ",
      "mi banh v",
      "mi banh vu",
      "mi banh vun",
      "mi banh vung",
      "m",
      "mi",
      "mi ",
      "mi v",
      "mi vu",
      "mi vun",
      "mi vung",
      "mi vung ",
      "mi vung b",
      "mi vung ba",
      "mi vung ban",
      "mi vung banh",
      "v",
      "vu",
      "vun",
      "vung",
      "vung ",
      "vung b",
      "vung ba",
      "vung ban",
      "vung banh",
      "vung banh ",
      "vung banh m",
      "vung banh mi",
      "v",
      "vu",
      "vun",
      "vung",
      "vung ",
      "vung m",
      "vung mi",
      "vung mi ",
      "vung mi b",
      "vung mi ba",
      "vung mi ban",
      "vung mi banh",
    ],
    price: 24000,
    discount: 5,
    productImage:
      "http://media.dulich24.com.vn/bai-viet/nhung-mon-dac-san-noi-tieng-vung-tay-bac-40090222/34b14f6e-466e-4280-b1f5-df690658b049.jpg",
  },
  {
    id: "E2xNhX5DumicnQoD6rIw",
    rating: 4,
    productImage:
      "http://media.dulich24.com.vn/bai-viet/6-dac-san-lai-chau-nen-thu-tren-duong-du-lich-45105135/6-dac-san-lai-chau-nen-thu-tren-duong-du-lich-1.jpg",
    keywords: ["q", "qu", "qua", "quat"],
    description: "Đặc sản miền núi",
    discount: 18,
    unit: "Quả",
    productName: "Lợn cắp nách",
    categoryId: "X63OeZXLKAqyVcAm38aT",
    quantity: 100,
    price: 88000,
    createdDate: {
      seconds: 1627277982,
      nanoseconds: 606000000,
    },
  },
  {
    id: "iYzD7lXqxYgiu1imSshQ",
    rating: 4,
    discount: 15,
    productName: "Bê mộc châu",
    createdDate: {
      seconds: 1627277867,
      nanoseconds: 53000000,
    },
    keywords: [
      "c",
      "ch",
      "chu",
      "chuo",
      "chuoi",
      "chuoi ",
      "chuoi t",
      "chuoi ti",
      "chuoi tie",
      "chuoi tieu",
      "t",
      "ti",
      "tie",
      "tieu",
      "tieu ",
      "tieu c",
      "tieu ch",
      "tieu chu",
      "tieu chuo",
      "tieu chuoi",
    ],
    unit: "Quả",
    categoryId: "X63OeZXLKAqyVcAm38aT",
    description: "Số lượng lớn",
    price: 88000,
    quantity: 21,
    productImage:
      "http://media.dulich24.com.vn/diemden/cao-nguyen-moc-chau-son-la-3356/cao-nguyen-moc-chau-11.jpg",
  },
  {
    id: "Wjc8fbJkpSRIpBUi9LgD",
    unit: "kg",
    productName: "Sâu chít điện biên",
    rating: 3,
    discount: 80,
    description: "Nuôi môi trường nước ngọt",
    keywords: [
      "c",
      "ca",
      "ca ",
      "ca n",
      "ca nu",
      "n",
      "nu",
      "nu ",
      "nu c",
      "nu ca",
    ],
    quantity: 31,
    createdDate: {
      seconds: 1627277798,
      nanoseconds: 316000000,
    },
    productImage:
      "http://media.dulich24.com.vn/bai-viet/nhung-mon-dac-san-noi-tieng-vung-tay-bac-40090222/74fa5b92-9517-4b6b-9965-a2007795cb1f.jpg",
    updatedDate: {
      seconds: 1627277803,
      nanoseconds: 948000000,
    },
    price: 46000,
    categoryId: "jqaq8roGL4QRZKn9Hpc7",
  },
  {
    id: "TNqaxRJ6uSsS6evoppLT",
    productImage:
      "http://media.dulich24.com.vn/bai-viet/6-dac-san-lai-chau-nen-thu-tren-duong-du-lich-45105135/6-dac-san-lai-chau-nen-thu-tren-duong-du-lich-2.jpg",
    description: "Xẻ thịt trong ngày",
    categoryId: "jqaq8roGL4QRZKn9Hpc7",
    price: 78000,
    quantity: 100,
    keywords: [
      "b",
      "ba",
      "bap",
      "bap ",
      "bap b",
      "bap bo",
      "b",
      "bo",
      "bo ",
      "bo b",
      "bo ba",
      "bo bap",
    ],
    unit: "kg",
    rating: 3,
    discount: 10,
    productName: "Cá bống vùi tro",
    createdDate: {
      seconds: 1627277746,
      nanoseconds: 648000000,
    },
  },

  {
    id: "Hr0OdfA2CPJTPcIUW8JA",
    unit: "kg",
    price: 67000,
    discount: 32,
    keywords: [
      "d",
      "da",
      "dau",
      "dau ",
      "dau b",
      "dau ba",
      "dau bap",
      "b",
      "ba",
      "bap",
      "bap ",
      "bap d",
      "bap da",
      "bap dau",
    ],
    productImage:
      "https://firebasestorage.googleapis.com/v0/b/ecommerce-da802.appspot.com/o/v21.jpg?alt=media&token=773ba1fa-8c9d-42e6-a396-8d7a76b4b54b",
    quantity: 41,
    createdDate: {
      seconds: 1627277594,
      nanoseconds: 808000000,
    },
    productName: "Đậu bắp",
    categoryId: "Y4wlWVRg8AUjnGt8zjJC",
    description: "Phù hợp món nướng",
    rating: 3,
  },
  {
    id: "dYWGsGiUWNvjzmycDJR4",
    createdDate: {
      seconds: 1627277554,
      nanoseconds: 841000000,
    },
    keywords: [
      "c",
      "cu",
      "cui",
      "cui ",
      "cui d",
      "cui du",
      "cui dua",
      "d",
      "du",
      "dua",
      "dua ",
      "dua c",
      "dua cu",
      "dua cui",
    ],
    productName: "Cùi dừa",
    price: 71000,
    categoryId: "wVaMcDH4yni65ls9aY3C",
    quantity: 10,
    description: "Nạo từ những quả dừa",
    discount: 20,
    rating: 4,
    unit: "Sản phẩm",
    productImage:
      "https://firebasestorage.googleapis.com/v0/b/ecommerce-da802.appspot.com/o/o3.jpg?alt=media&token=8e62563d-b8c1-4851-aae2-951f438b4bf8",
  },
  {
    id: "G6rpXqqC8SmWdWzRISYs",
    productName: "Hạt đỗ",
    rating: 4,
    categoryId: "wVaMcDH4yni65ls9aY3C",
    createdDate: {
      seconds: 1627277519,
      nanoseconds: 175000000,
    },
    keywords: [
      "h",
      "ha",
      "hat",
      "hat ",
      "hat d",
      "hat do",
      "d",
      "do",
      "do ",
      "do h",
      "do ha",
      "do hat",
    ],
    unit: "Sản phẩm",
    productImage:
      "https://firebasestorage.googleapis.com/v0/b/ecommerce-da802.appspot.com/o/o9.jpg?alt=media&token=e4a2a036-dcd7-4781-844e-3fc94c6ac06b",
    discount: 60,
    description: "Đỗ lê men",
    price: 14000,
    quantity: 100,
  },
  {
    id: "1Cfjz85fhM6TIw9hGdPw",
    price: 134000,
    quantity: 2,
    productImage:
      "https://firebasestorage.googleapis.com/v0/b/ecommerce-da802.appspot.com/o/05.jpg?alt=media&token=1577aaac-a756-45a4-b800-31961cf3f86a",
    createdDate: {
      seconds: 1627277474,
      nanoseconds: 538000000,
    },
    discount: 50,
    productName: "Cá chuồn 123",
    categoryId: "jqaq8roGL4QRZKn9Hpc7",
    description: "Cá ngoài biển mặn 123",
    unit: "g",
    keywords: [
      "c",

      "ca",
      "ca ",
      "ca c",
      "ca ch",
      "ca chu",
      "ca chuo",
      "ca chuon",
      "c",
      "ch",
      "chu",
      "chuo",
      "chuon",
      "chuon ",
      "chuon c",
      "chuon ca",
    ],
    rating: 3,
  },

  {
    id: "WXzW6oozaokDarx3LPKO",
    createdDate: {
      seconds: 1627277374,
      nanoseconds: 834000000,
    },
    price: 57000,
    unit: "Sản phẩm",
    rating: 2,
    productName: "Tỏi nghiền",
    description: "Gia vị tỏi ớt",
    quantity: 100,
    productImage:
      "https://firebasestorage.googleapis.com/v0/b/ecommerce-da802.appspot.com/o/s9.jpg?alt=media&token=5859cce4-1cd3-4df3-b9b9-51db221b023a",
    discount: 60,
    categoryId: "D12YC358aOe71ZVhrdOf",
    keywords: [
      "t",
      "to",
      "toi",
      "toi ",
      "toi n",
      "toi ng",
      "toi ngh",
      "toi nghi",
      "toi nghie",
      "toi nghien",
      "n",
      "ng",
      "ngh",
      "nghi",
      "nghie",
      "nghien",
      "nghien ",
      "nghien t",
      "nghien to",
      "nghien toi",
    ],
  },
  {
    id: "lTqE7bwJ7ne17NHQzC6I",
    keywords: [
      "s",
      "su",
      "sua",
      "sua ",
      "sua d",
      "sua du",
      "sua dua",
      "d",
      "du",
      "dua",
      "dua ",
      "dua s",
      "dua su",
      "dua sua",
    ],
    productImage:
      "https://firebasestorage.googleapis.com/v0/b/ecommerce-da802.appspot.com/o/s12.jpg?alt=media&token=86de0a16-3f36-444f-967c-5ddcd5cc7b64",
    price: 51000,
    categoryId: "WLCBEkRzCY5H703DUO4o",
    productName: "Sữa dừa",
    unit: "Sản phẩm",
    quantity: 31,
    createdDate: {
      seconds: 1627277328,
      nanoseconds: 941000000,
    },
    description: "Nguyên chất 100% tự nhiên",
    rating: 2,
    discount: 32,
  },
  {
    id: "FA2WgNwov3ixt7cBFega",
    createdDate: {
      seconds: 1627277266,
      nanoseconds: 297000000,
    },
    unit: "kg",
    price: 27000,
    productImage:
      "https://firebasestorage.googleapis.com/v0/b/ecommerce-da802.appspot.com/o/v9.jpg?alt=media&token=5a4a44c3-dad9-4276-9cf9-3568992986fa",
    discount: 15,
    description: "Rau được trồng hưu cơ",
    rating: 4,
    quantity: 100,
    productName: "Cải lơ",
    categoryId: "Y4wlWVRg8AUjnGt8zjJC",
    keywords: [
      "c",
      "ca",
      "cai",
      "cai ",
      "cai l",
      "cai lo",
      "l",
      "lo",
      "lo ",
      "lo c",
      "lo ca",
      "lo cai",
    ],
  },
  {
    id: "j8bu2hpYygc572Zwe3c5",
    productImage:
      "https://firebasestorage.googleapis.com/v0/b/ecommerce-da802.appspot.com/o/v17.jpg?alt=media&token=e53d6797-5f67-4e20-b3c6-74e21b032dfb",
    price: 123000,
    keywords: [
      "n",
      "ng",
      "ngo",
      "ngo ",
      "ngo n",
      "ngo ne",
      "ngo nep",
      "n",
      "ne",
      "nep",
      "nep ",
      "nep n",
      "nep ng",
      "nep ngo",
    ],
    createdDate: {
      seconds: 1627276925,
      nanoseconds: 246000000,
    },
    unit: "kg",
    quantity: 21,
    discount: 71,
    rating: 3,
    description: "Ngô nếp số lượng ít",
    categoryId: "Y4wlWVRg8AUjnGt8zjJC",
    productName: "Ngô nếp",
  },
];
